[package]
name = "rust_bible_lookup"
version = "0.1.0"
authors = ["Josiah Lansford <39782615+josassy@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
